using Sqordia.Domain.Common;
using Sqordia.Domain.Enums;

namespace Sqordia.Domain.Entities;

/// <summary>
/// Discount coupon that can be applied to subscription purchases.
/// Coupons are generated by the subscription intelligence engine or manually by admins.
/// </summary>
public class Coupon : BaseAuditableEntity
{
    public string Code { get; private set; } = null!;
    public string Description { get; private set; } = null!;

    /// <summary>
    /// Discount percentage (0-50)
    /// </summary>
    public int DiscountPercent { get; private set; }

    /// <summary>
    /// Applicable plan types (null = all plans)
    /// </summary>
    public SubscriptionPlanType? TargetPlanType { get; private set; }

    /// <summary>
    /// Promotion type that triggered this coupon (null = manual/admin)
    /// </summary>
    public string? PromotionType { get; private set; }

    public DateTime ValidFrom { get; private set; }
    public DateTime ValidUntil { get; private set; }

    /// <summary>
    /// Max total redemptions (0 = unlimited)
    /// </summary>
    public int MaxRedemptions { get; private set; }

    /// <summary>
    /// Max redemptions per organization (0 = unlimited)
    /// </summary>
    public int MaxRedemptionsPerOrg { get; private set; } = 1;

    public int TimesRedeemed { get; private set; }
    public bool IsActive { get; private set; } = true;

    /// <summary>
    /// If set, this coupon is for a specific organization (personalized offer)
    /// </summary>
    public Guid? OrganizationId { get; private set; }

    /// <summary>
    /// Stripe coupon ID (synced to Stripe for checkout integration)
    /// </summary>
    public string? StripeCouponId { get; private set; }

    // Navigation
    public ICollection<CouponRedemption> Redemptions { get; private set; } = new List<CouponRedemption>();

    private Coupon() { } // EF Core

    public Coupon(
        string code,
        string description,
        int discountPercent,
        DateTime validFrom,
        DateTime validUntil,
        int maxRedemptions = 0,
        SubscriptionPlanType? targetPlanType = null,
        string? promotionType = null,
        Guid? organizationId = null)
    {
        Code = code?.ToUpperInvariant() ?? throw new ArgumentNullException(nameof(code));
        Description = description ?? throw new ArgumentNullException(nameof(description));
        DiscountPercent = Math.Clamp(discountPercent, 0, 50);
        ValidFrom = validFrom;
        ValidUntil = validUntil;
        MaxRedemptions = maxRedemptions;
        TargetPlanType = targetPlanType;
        PromotionType = promotionType;
        OrganizationId = organizationId;
    }

    public bool IsValid()
    {
        return IsActive
            && DateTime.UtcNow >= ValidFrom
            && DateTime.UtcNow <= ValidUntil
            && (MaxRedemptions == 0 || TimesRedeemed < MaxRedemptions);
    }

    public bool CanBeRedeemedBy(Guid organizationId)
    {
        if (!IsValid()) return false;
        if (OrganizationId.HasValue && OrganizationId.Value != organizationId) return false;
        return true;
    }

    public void Redeem()
    {
        TimesRedeemed++;
    }

    public void Deactivate()
    {
        IsActive = false;
    }

    public void SetStripeCouponId(string stripeCouponId)
    {
        StripeCouponId = stripeCouponId;
    }
}
